"""Write a BlendCap retarget preset JSON into the user config folder."""

import json
import os
import re
import shutil
import tempfile
import unicodedata

import bpy


def _user_preset_dir():
    base = bpy.utils.user_resource("CONFIG")
    directory = os.path.join(base, "blendcap", "retarget_maps")
    os.makedirs(directory, exist_ok=True)
    return directory


def _safe_filename(name):
    s = unicodedata.normalize("NFKC", name or "").strip()
    s = re.sub(r"[^\w.\-]+", "_", s, flags=re.UNICODE)
    s = re.sub(r"_+", "_", s).strip("._")
    return s[:60] or "rig"


def write_preset(target_rig_name, pairs, source_prefix="", *, return_backup=False):
    """Atomically write a preset and preserve one exact previous backup.

    Normal one-click retargeting does not call this function; disk output is
    an explicit advanced operation. Existing bytes are copied to ``.bak``
    before replacement and a temporary JSON file is validated first.
    """
    safe = _safe_filename(target_rig_name)
    path = os.path.join(_user_preset_dir(), f"blendcap_motion_bridge_{safe}.json")
    data = {
        "name": f"BlendCap Motion Bridge: {target_rig_name}",
        "version": 1,
        "target_kind": "generic",
        "namespace_strip": "",
        "auto_bake_ik": False,
        "_note": "Generated by BlendCap Motion Bridge from the current MMD armature.",
        "pairs": pairs,
    }
    if source_prefix:
        data["source_prefix"] = source_prefix
    encoded = (json.dumps(data, indent=2, ensure_ascii=False) + "\n").encode("utf-8")
    backup = ""
    if os.path.isfile(path):
        with open(path, "rb") as existing_file:
            existing = existing_file.read()
        if existing == encoded:
            return (path, backup) if return_backup else path
        backup = path + ".bak"
        backup_tmp = backup + ".tmp"
        shutil.copy2(path, backup_tmp)
        os.replace(backup_tmp, backup)

    fd, temporary = tempfile.mkstemp(prefix=".blendcap_motion_bridge_", suffix=".json.tmp", dir=os.path.dirname(path))
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(encoded)
            handle.flush()
            os.fsync(handle.fileno())
        with open(temporary, encoding="utf-8") as check:
            verified = json.load(check)
        if verified.get("pairs") != pairs:
            raise ValueError("preset verification failed: pair table changed")
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    return (path, backup) if return_backup else path
